"""ゲーム全体の定数・設定の集約（Phase 0 土台）。"""

from basketball_sim.config.game_constants import (
    CLOCK_SECONDS_PER_REGULATION_QUARTER,
    FORFEIT_SCORE,
    GAME_ID,
    LEAGUE_ONCOURT_ASIA_NATURALIZED_CAP,
    LEAGUE_ONCOURT_FOREIGN_CAP,
    LEAGUE_ROSTER_ASIA_NATURALIZED_CAP,
    LEAGUE_ROSTER_FOREIGN_CAP,
    MINIMUM_ACTIVE_PLAYERS_FOR_GAME,
    PAYLOAD_SCHEMA_VERSION,
    REGULATION_QUARTERS,
)

__all__ = [
    "CLOCK_SECONDS_PER_REGULATION_QUARTER",
    "FORFEIT_SCORE",
    "GAME_ID",
    "LEAGUE_ONCOURT_ASIA_NATURALIZED_CAP",
    "LEAGUE_ONCOURT_FOREIGN_CAP",
    "LEAGUE_ROSTER_ASIA_NATURALIZED_CAP",
    "LEAGUE_ROSTER_FOREIGN_CAP",
    "MINIMUM_ACTIVE_PLAYERS_FOR_GAME",
    "PAYLOAD_SCHEMA_VERSION",
    "REGULATION_QUARTERS",
]
